<a href="https://colab.research.google.com/github/infoankitakm2609-blip/Machine-Learning-College-Lab/blob/main/ml_oct8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd

In [65]:
import json

In [66]:
df =pd.read_json("student_data.json")

In [67]:
print(df)

    student_id            name     age  gender     city course  marks  \
0          101   Rahul Sharma       20    Male  Lucknow    CSE   85.0
1          102     Priya Singh      21  Female  lucknow    CSE   90.0
2          103      amit kumar      19    Male   Kanpur    cse   78.0
3          104     Sneha Verma      22  FEMALE  Lucknow    CSE    NaN
4          105     Rohit Gupta      20    male   Kanpur    CSE   67.0
5          106    Anjali Mehta    None  Female    Delhi    ECE   88.0
6          107     Vikas Yadav      21    Male    delhi    ece   74.0
7          108      Neha Singh      20  Female  Lucknow    CSE   92.0
8          109     Arjun Patel      19    Male   Kanpur    CSE   56.0
9          110     Riya Sharma      20  Female  Lucknow    ECE   81.0
10         111    Rahul Sharma      20    Male  Lucknow    CSE   85.0
11         112    Karan Singh   twenty    MALE   Kanpur    CSE   73.0
12         113     Pooja Gupta      21  Female    Delhi    ECE   99.0
13         114    Manish Kumar      23    Male  Lucknow    CSE  -10.0
14         115       Divya Rao      20  Female   Kanpur    CSE   91.0
15         116      Akash Jain      21    Male    Delhi    ECE   65.0
16         117     Simran Kaur      20  Female  Lucknow    CSE   88.0
17         118    Aditya Verma      19    Male   Kanpur    CSE   45.0
18         119     Nisha Patel      20  Female    Delhi    ECE   76.0
19         120     Varun Singh      21    Male  Lucknow    CSE   82.0
20         120     Varun Singh      21    Male  Lucknow    CSE   82.0
21         121            None      20  Female   Kanpur    CSE   79.0
22         122       Harsh Raj      20    Male  Lucknow    CSE  110.0
23         123     Tanya Gupta      21  Female    Delhi    ECE   87.0
24         124    Deepak Singh      22    Male   Kanpur    CSE   69.0
25         125    Megha Sharma      20  Female  Lucknow    CSE   94.0

    attendance fees_paid joining_date              email
0         92.0       Yes   2024-07-15    rahul@gmail.com
1         95.0       Yes   15-07-2024    priya@gmail.com
2         88.0        No   2024/07/20     amit@gmail.com
3         91.0       Yes   2024-07-18    sneha@gmail.com
4        105.0       Yes   2024-07-21    rohit@gmail.com
5         89.0       Yes   2024-07-22       anjali@gmail
6         76.0        No   2024-07-25    vikas@gmail.com
7         94.0       Yes   2024-07-26               None
8         72.0        No   2024-07-28    arjun@gmail.com
9         87.0       Yes   2024-07-29     riya@gmail.com
10        92.0       Yes   2024-07-15    rahul@gmail.com
11        82.0       YES   2024-08-01    karan@gmail.com
12        97.0       Yes   2024-08-03    pooja@gmail.com
13        85.0        No   2024-08-05   manish@gmail.com
14         NaN       Yes   2024-08-06    divya@gmail.com
15        78.0        No   2024-08-08   akash@gmail.com
16        90.0       Yes   2024-08-10   simran@gmail.com
17        68.0        No   2024-08-11   aditya@gmail.com
18        84.0       Yes   2024-08-12    nisha@gmail.com
19        89.0       Yes   2024-08-13    varun@gmail.com
20        89.0       Yes   2024-08-13    varun@gmail.com
21        86.0       Yes   2024-08-15    meena@gmail.com
22        93.0       Yes   2024-08-16    harsh@gmail.com
23        88.0        No   2024-08-18    tanya@gmail.com
24        81.0        No   2024-08-20   deepak@gmail.com
25        96.0       Yes   2024-08-21    megha@gmail.com

In [68]:
df.isnull()

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,joining_date,email
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,True,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,True,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False

In [69]:
df.isnull().sum()

student_id      0
name            1
age             1
gender          0
city            0
course          0
marks           1
attendance      1
fees_paid       0
joining_date    0
email           1
dtype: int64

In [70]:
df.isnull().sum().sum()

np.int64(5)

In [71]:
df.notnull()

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,joining_date,email
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,False,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
5,True,True,False,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,False
8,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,False,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True
21,True,False,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,True

In [72]:
df_copy = df.copy()

In [73]:
df_copy1 = df_copy.copy()

In [74]:
df_copy1['name'] = df_copy1["name"].fillna("Unknown")

In [75]:
df_copy1['age']=pd.to_numeric(df_copy1['age'],errors='coerce')

In [77]:
df_copy1['age'] = df_copy1['age'].fillna(round(df_copy1["age"].mean()))

In [78]:
df_copy1["age"] = df_copy1["age"].astype("int")

In [79]:
df.dtypes

student_id        int64
name             object
age              object
gender           object
city             object
course           object
marks           float64
attendance      float64
fees_paid        object
joining_date     object
email            object
dtype: object

In [80]:
df_copy1

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,joining_date,email
0,101,Rahul Sharma,20,Male,Lucknow,CSE,85.0,92.0,Yes,2024-07-15,rahul@gmail.com
1,102,Priya Singh,21,Female,lucknow,CSE,90.0,95.0,Yes,15-07-2024,priya@gmail.com
2,103,amit kumar,19,Male,Kanpur,cse,78.0,88.0,No,2024/07/20,amit@gmail.com
3,104,Sneha Verma,22,FEMALE,Lucknow,CSE,NaN,91.0,Yes,2024-07-18,sneha@gmail.com
4,105,Rohit Gupta,20,male,Kanpur,CSE,67.0,105.0,Yes,2024-07-21,rohit@gmail.com
5,106,Anjali Mehta,20,Female,Delhi,ECE,88.0,89.0,Yes,2024-07-22,anjali@gmail
6,107,Vikas Yadav,21,Male,delhi,ece,74.0,76.0,No,2024-07-25,vikas@gmail.com
7,108,Neha Singh,20,Female,Lucknow,CSE,92.0,94.0,Yes,2024-07-26,None
8,109,Arjun Patel,19,Male,Kanpur,CSE,56.0,72.0,No,2024-07-28,arjun@gmail.com
9,110,Riya Sharma,20,Female,Lucknow,ECE,81.0,87.0,Yes,2024-07-29,riya@gmail.com
10,111,Rahul Sharma,20,Male,Lucknow,CSE,85.0,92.0,Yes,2024-07-15,rahul@gmail.com
11,112,Karan Singh,20,MALE,Kanpur,CSE,73.0,82.0,YES,2024-08-01,karan@gmail.com
12,113,Pooja Gupta,21,Female,Delhi,ECE,99.0,97.0,Yes,2024-08-03,pooja@gmail.com
13,114,Manish Kumar,23,Male,Lucknow,CSE,-10.0,85.0,No,2024-08-05,manish@gmail.com
14,115,Divya Rao,20,Female,Kanpur,CSE,91.0,NaN,Yes,2024-08-06,divya@gmail.com
15,116,Akash Jain,21,Male,Delhi,ECE,65.0,78.0,No,2024-08-08,akash@gmail.com
16,117,Simran Kaur,20,Female,Lucknow,CSE,88.0,90.0,Yes,2024-08-10,simran@gmail.com
17,118,Aditya Verma,19,Male,Kanpur,CSE,45.0,68.0,No,2024-08-11,aditya@gmail.com
18,119,Nisha Patel,20,Female,Delhi,ECE,76.0,84.0,Yes,2024-08-12,nisha@gmail.com
19,120,Varun Singh,21,Male,Lucknow,CSE,82.0,89.0,Yes,2024-08-13,varun@gmail.com
20,120,Varun Singh,21,Male,Lucknow,CSE,82.0,89.0,Yes,2024-08-13,varun@gmail.com
21,121,Unknown,20,Female,Kanpur,CSE,79.0,86.0,Yes,2024-08-15,meena@gmail.com
22,122,Harsh Raj,20,Male,Lucknow,CSE,110.0,93.0,Yes,2024-08-16,harsh@gmail.com
23,123,Tanya Gupta,21,Female,Delhi,ECE,87.0,88.0,No,2024-08-18,tanya@gmail.com
24,124,Deepak Singh,22,Male,Kanpur,CSE,69.0,81.0,No,2024-08-20,deepak@gmail.com
25,125,Megha Sharma,20,Female,Lucknow,CSE,94.0,96.0,Yes,2024-08-21,megha@gmail.com

In [81]:
df_copy1.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22    False
23    False
24    False
25    False
dtype: bool